### ISSUE TITLE
Add cities gives message critical error

### ISSUE THREAD

**Issue by jlb-1985** [Beee4life/acf-city-selector#129]
Hello,

I've tried to add a new country (Belgium) and cities, when I click add I get the message 
"A critical error has occurred on this site. Check your site administrator email inbox for instructions."

When I want to add via CSV I also get this message.

![image](https://github.com/Beee4life/acf-city-selector/assets/130216366/b30f787c-64cf-4eac-8ee4-b4a86aa6eef1)

**Comment by jlb-1985** [comment]
The function remove transients gives also a critical error message.

**Comment by jlb-1985** [comment]
I tried to deactive and remove the plugin, but it refuses it. I get the same critical error message. 
There is no conflict with other plugins, because I deactivated the other plugins and still get these critical error messages.

**Comment by Beee4life** [comment]
That should have been fixed in the last release.

Can you plz add a copy of the error here ?

**Comment by jlb-1985** [comment]
I still have this problem. Is there something you can do? 
I can give you my login to see for yourself.

**Comment by Beee4life** [comment]
Can you plz add a copy of the error here ?

**Comment by jlb-1985** [comment]
In Dutch: "Er heeft zich een kritieke fout voorgedaan op deze site. Controleer je site beheerder e-mail inbox voor instructies.
[Meer informatie over probleemoplossing in WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)"

Translated in English: "A critical error has occurred on this site. Check your site administrator email inbox for instructions. 
[Learn more about troubleshooting in WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)"

This is the only error message I get.

**Comment by Beee4life** [comment]
That is the on screen message. 

You need to activate `WP_DEBUG_LOG` error notices get logged in `/wp-content/debug.log`. Explained [here](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/).

That shows more info.

**Comment by jlb-1985** [comment]
<html>
<body>

PHP Fatal | Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "i will try acfcs_delete_transients" not found or invalid function nameStack trace:#0 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()#1 /wp-includes/plugin.php(517): WP_Hook->do_action()#2 /wp-content/plugins/acf-city-selector/inc/form-handling.php(145): do_action()#3 /wp-includes/class-wp-hook.php(324): acfcs_delete_all_transients()#4 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()#5 /wp-includes/plugin.php(517): WP_Hook->do_action()#6 /wp-admin/admin.php(175): do_action()#7 /wp-admin/options-general.php(10): require_once('/home/deb141886...')#8 {main} thrown in /wp-includes/class-wp-hook.php on line 324WordPress coreFile: /wp-includes/class-wp-hook.phpLine: 324
-- | --



</body>
</html>PHP Fatal	Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "i will try acfcs_delete_transients" not found or invalid function name
Stack trace:
#0 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#1 /wp-includes/plugin.php(517): WP_Hook->do_action()
#2 /wp-content/plugins/acf-city-selector/inc/form-handling.php(145): do_action()
#3 /wp-includes/class-wp-hook.php(324): acfcs_delete_all_transients()
#4 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /wp-admin/admin.php(175): do_action()
#7 /wp-admin/options-general.php(10): require_once('/home/deb141886...')
#8 {main} thrown in /wp-includes/class-wp-hook.php on line 324
WordPress core
File: [/wp-includes/class-wp-hook.php](https://github.com/WordPress/wordpress-develop/blob/6.5.2/src/wp-includes/class-wp-hook.php)
Line: 324

**Comment by jlb-1985** [comment]
![image](https://github.com/Beee4life/acf-city-selector/assets/130216366/71e8eab7-bd6b-4097-babd-d7f4c9558065)

**Comment by jlb-1985** [comment]
If I want to import countries 

![image](https://github.com/Beee4life/acf-city-selector/assets/130216366/7a95d423-7ecb-480e-a0f5-344c1b713ca4)

**Comment by jlb-1985** [comment]
If I want to import CSV data

![image](https://github.com/Beee4life/acf-city-selector/assets/130216366/011cd220-e6dc-436b-a794-061ada2d48d0)

**Comment by Beee4life** [comment]
Now those help :)

As you can see, it looks like the function `acfcs_delete_transients` can not be found.

I would l have to dig into it but now I have a handle.

**Comment by Beee4life** [comment]
It's fixed in https://github.com/Beee4life/acf-city-selector/releases/tag/1.13.0.

WP update will come a bit later today.

**Comment by jlb-1985** [comment]
Thank you very much!!!

**Comment by Beee4life** [comment]
No prob.
